In [5]:
import pandas
import rdkit

print("Python:", sys.version)
print("pandas:", pandas.__version__)
print("RDKit:", rdkit.__version__)

Python: 3.11.15 | packaged by Anaconda, Inc. | (main, Jun 11 2026, 15:12:53) [MSC v.1942 64 bit (AMD64)]
pandas: 3.0.3
RDKit: 2025.09.6

In [2]:
import sys
sys.path.append("../src")
from find_the_target import find_the_target

In [4]:
result = find_the_target("chembl_36.db", "CHEMBL25")
result.head(10)

,pref_name,target_type,chembl_id,standard_type,standard_relation,standard_value,standard_units
0,Unchecked,UNCHECKED,CHEMBL612545,IC50,=,3.460000e+04,nM
1,Unchecked,UNCHECKED,CHEMBL612545,IC50,=,3.490000e+04,nM
2,Prostaglandin G/H synthase 2,SINGLE PROTEIN,CHEMBL230,IC50,=,6.250000e+04,nM
3,Prostaglandin G/H synthase 1,SINGLE PROTEIN,CHEMBL2949,IC50,=,1.250000e+04,nM
4,Unchecked,UNCHECKED,CHEMBL612545,IC50,>,1.000000e+06,nM
5,Oryctolagus cuniculus,ORGANISM,CHEMBL374,IC50,>,1.000000e+06,nM
6,Cyclooxygenase,PROTEIN FAMILY,CHEMBL2096674,IC50,=,1.500000e+06,nM
7,Homo sapiens,ORGANISM,CHEMBL372,IC50,=,1.850000e+05,nM
8,Homo sapiens,ORGANISM,CHEMBL372,IC50,=,7.000000e+10,nM
9,Oryctolagus cuniculus,ORGANISM,CHEMBL374,IC50,=,1.600000e+04,nM

In [5]:
result = find_the_target("chembl_36.db", "CC(=O)OC1=CC=CC=C1C(=O)O")
result.head(10)

,pref_name,target_type,chembl_id,standard_type,standard_relation,standard_value,standard_units
0,Unchecked,UNCHECKED,CHEMBL612545,IC50,=,3.460000e+04,nM
1,Unchecked,UNCHECKED,CHEMBL612545,IC50,=,3.490000e+04,nM
2,Prostaglandin G/H synthase 2,SINGLE PROTEIN,CHEMBL230,IC50,=,6.250000e+04,nM
3,Prostaglandin G/H synthase 1,SINGLE PROTEIN,CHEMBL2949,IC50,=,1.250000e+04,nM
4,Unchecked,UNCHECKED,CHEMBL612545,IC50,>,1.000000e+06,nM
5,Oryctolagus cuniculus,ORGANISM,CHEMBL374,IC50,>,1.000000e+06,nM
6,Cyclooxygenase,PROTEIN FAMILY,CHEMBL2096674,IC50,=,1.500000e+06,nM
7,Homo sapiens,ORGANISM,CHEMBL372,IC50,=,1.850000e+05,nM
8,Homo sapiens,ORGANISM,CHEMBL372,IC50,=,7.000000e+10,nM
9,Oryctolagus cuniculus,ORGANISM,CHEMBL374,IC50,=,1.600000e+04,nM

In [7]:
result["target_type"].value_counts()

target_type
SINGLE PROTEIN     195
CELL-LINE          124
ORGANISM            40
NON-MOLECULAR       38
UNCHECKED           22
TISSUE              10
PROTEIN COMPLEX      3
PROTEIN FAMILY       2
ADMET                2
Name: count, dtype: int64

In [6]:
#Filter results to single-protein targets if needed
result[result["target_type"] == "SINGLE PROTEIN"]

,pref_name,target_type,chembl_id,standard_type,standard_relation,standard_value,standard_units
2,Prostaglandin G/H synthase 2,SINGLE PROTEIN,CHEMBL230,IC50,=,62500.0,nM
3,Prostaglandin G/H synthase 1,SINGLE PROTEIN,CHEMBL2949,IC50,=,12500.0,nM
14,Prostaglandin G/H synthase 1,SINGLE PROTEIN,CHEMBL2949,IC50,=,1280000.0,nM
15,Prostaglandin G/H synthase 2,SINGLE PROTEIN,CHEMBL230,IC50,=,18000000.0,nM
27,Prostaglandin G/H synthase 1,SINGLE PROTEIN,CHEMBL2949,IC50,=,240000.0,nM
...,...,...,...,...,...,...,...
426,Carbonic anhydrase 2,SINGLE PROTEIN,CHEMBL205,Ki,>,100000.0,nM
427,Carbonic anhydrase 4,SINGLE PROTEIN,CHEMBL3729,Ki,>,100000.0,nM
428,Carbonic anhydrase 7,SINGLE PROTEIN,CHEMBL2326,Ki,>,100000.0,nM
429,Carbonic anhydrase 9,SINGLE PROTEIN,CHEMBL3594,Ki,>,100000.0,nM
430,Carbonic anhydrase 12,SINGLE PROTEIN,CHEMBL3242,Ki,>,100000.0,nM